-- MySQL Script generated by MySQL Workbench
-- Tue Dec  6 13:53:07 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema portfoliodb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema portfoliodb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `portfoliodb` DEFAULT CHARACTER SET utf8 ;
USE `portfoliodb` ;

-- -----------------------------------------------------
-- Table `portfoliodb`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfoliodb`.`admin` (
  `usuario` VARCHAR(20) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`usuario`),
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC) ,
  UNIQUE INDEX `contraseña_UNIQUE` (`contraseña` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfoliodb`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfoliodb`.`persona` (
  `titulo` VARCHAR(60) NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `foto` VARCHAR(300) NOT NULL,
  `banner` VARCHAR(300) NOT NULL,
  `admin_usuario` VARCHAR(20) NOT NULL,
  UNIQUE INDEX `foto_UNIQUE` (`foto` ASC) ,
  UNIQUE INDEX `banner_UNIQUE` (`banner` ASC) ,
  PRIMARY KEY (`admin_usuario`),
  CONSTRAINT `fk_informacionPersonal_admin`
    FOREIGN KEY (`admin_usuario`)
    REFERENCES `portfoliodb`.`admin` (`usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfoliodb`.`experiencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfoliodb`.`experiencia` (
  `idexperiencia` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `periodo comienzo` DATE NULL,
  `imagen` VARCHAR(255) NULL,
  `link` VARCHAR(300) NULL,
  `informacionPersonal_admin_usuario` VARCHAR(20) NOT NULL,
  `periodoFinal` DATE NULL,
  PRIMARY KEY (`idexperiencia`, `informacionPersonal_admin_usuario`),
  INDEX `fk_experiencia_informacionPersonal1_idx` (`informacionPersonal_admin_usuario` ASC) ,
  CONSTRAINT `fk_experiencia_informacionPersonal1`
    FOREIGN KEY (`informacionPersonal_admin_usuario`)
    REFERENCES `portfoliodb`.`persona` (`admin_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfoliodb`.`educacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfoliodb`.`educacion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(100) NULL,
  `tituloObtenido` VARCHAR(50) NULL,
  `periodoComienzo` DATE NULL,
  `imagen` VARCHAR(255) NULL,
  `link` VARCHAR(255) NULL,
  `informacionPersonal_admin_usuario` VARCHAR(20) NOT NULL,
  `periodoFinal` DATE NULL,
  PRIMARY KEY (`id`, `informacionPersonal_admin_usuario`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  INDEX `fk_educacion_informacionPersonal1_idx` (`informacionPersonal_admin_usuario` ASC) ,
  CONSTRAINT `fk_educacion_informacionPersonal1`
    FOREIGN KEY (`informacionPersonal_admin_usuario`)
    REFERENCES `portfoliodb`.`persona` (`admin_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfoliodb`.`hardSkill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfoliodb`.`hardSkill` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `progreso` TINYINT(100) NOT NULL,
  `color` VARCHAR(45) NOT NULL,
  `logo` VARCHAR(300) NULL,
  `informacionPersonal_admin_usuario` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`, `informacionPersonal_admin_usuario`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) ,
  INDEX `fk_hardSkill_informacionPersonal1_idx` (`informacionPersonal_admin_usuario` ASC) ,
  CONSTRAINT `fk_hardSkill_informacionPersonal1`
    FOREIGN KEY (`informacionPersonal_admin_usuario`)
    REFERENCES `portfoliodb`.`persona` (`admin_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfoliodb`.`softSkill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfoliodb`.`softSkill` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `progreso` TINYINT(100) NOT NULL,
  `informacionPersonal_admin_usuario` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`, `informacionPersonal_admin_usuario`),
  INDEX `fk_softSkill_informacionPersonal1_idx` (`informacionPersonal_admin_usuario` ASC),
  CONSTRAINT `fk_softSkill_informacionPersonal1`
    FOREIGN KEY (`informacionPersonal_admin_usuario`)
    REFERENCES `portfoliodb`.`persona` (`admin_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfoliodb`.`contacto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfoliodb`.`contacto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(40) NOT NULL,
  `correo` VARCHAR(60) NOT NULL,
  `mensaje` VARCHAR(300) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfoliodb`.`proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfoliodb`.`proyecto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `url` VARCHAR(300) NOT NULL,
  `imagen` VARCHAR(300) NOT NULL,
  `descripcion` VARCHAR(100) NULL,
  `informacionPersonal_admin_usuario` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`, `informacionPersonal_admin_usuario`),
  UNIQUE INDEX `url_UNIQUE` (`url` ASC) ,
  UNIQUE INDEX `imagen_UNIQUE` (`imagen` ASC),
  INDEX `fk_proyecto_informacionPersonal1_idx` (`informacionPersonal_admin_usuario` ASC) ,
  CONSTRAINT `fk_proyecto_informacionPersonal1`
    FOREIGN KEY (`informacionPersonal_admin_usuario`)
    REFERENCES `portfoliodb`.`persona` (`admin_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
